"""
Django settings for peacemindai project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from django.utils.translation import gettext_lazy as _

from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'jet',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'chat',
    'tailwind',
    'users',
    'main_app',
    'theme',
    'widget_tweaks',
    'django_browser_reload',
]

MIDDLEWARE = [
    "django_browser_reload.middleware.BrowserReloadMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ASGI_APPLICATION = 'peacemindai.asgi.application'

ROOT_URLCONF = 'peacemindai.urls'
AUTH_USER_MODEL='users.User'

TAILWIND_APP_NAME = 'theme'
INTERNAL_IPS = ['127.0.0.1']
NPM_BIN_PATH = r"C:\\Program Files\\nodejs\\npm.cmd"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# WSGI_APPLICATION = 'peacemindai.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


JET_DEFAULT_THEME = 'light-gray'
JET_SIDE_MENU_COMPACT = False
JET_INDEX_DASHBOARD = 'dashboard.CustomIndexDashboard'
JET_APP_INDEX_DASHBOARD = 'dashboard.CustomAppIndexDashboard'

JET_THEMES = [
    {
        'theme': 'default',
        'color': '#008374',  
        'title': 'Default'
    },
    {
        'theme': 'green',
        'color': '#00796b',  
        'title': 'Green'
    },
    {
        'theme': 'light-blue',
        'color': '#5eadde',
        'title': 'Light-Blue'
    },
    {
        'theme': 'light-gray',
        'color': '#222',
        'title': 'Light-gray'
    },
]

# Custom JET settings
JET_SIDE_MENU_ITEMS = [
    {'label': _('General'), 'items': [
        {'name': 'auth.user', 'label': _('Users'), 'url': 'admin:auth_user_changelist'},
        {'name': 'auth.group', 'label': _('Groups'), 'url': 'admin:auth_group_changelist'},
    ]},
    {'label': _('Applications'), 'items': [
        {'name': 'chat', 'label': _('Chat'), 'url': 'admin:chat_chat_changelist'},
        {'name': 'main_app', 'label': _('Main App'), 'url': 'admin:main_app_feedback_changelist'},
    ]},
]

JET_CHANGE_FORM_SIBLING_LINKS = True
JET_USE_PYCOINCOIN = True
JET_MODULE_INDEX_CHANGE_LIST = True
JET_MODULE_YANDEX_METRIKA = False

# JET UI Customization
JET_SIDE_MENU_CUSTOM_APPS = [
    ('auth', ['User', 'Group']),
    ('users', ['User']),
    ('chat', ['Chat']),
    ('main_app', ['Feedback']),
]

JET_INDEX_DASHBOARD = 'dashboard.CustomIndexDashboard'
JET_APP_INDEX_DASHBOARD = 'dashboard.CustomAppIndexDashboard'

# JET UI Settings
JET_UI_CUSTOMIZATIONS = {
    'show_menu': True,
    'show_menu_icons': True,
    'show_menu_compact': False,
    'show_menu_tooltips': True,
    'show_menu_user': True,
    'show_menu_apps': True,
    'show_menu_recent': True,
    'show_menu_bookmarks': True,
    'show_menu_related': True,
    'show_menu_related_models': True,
    'show_menu_related_apps': True,
    'show_menu_related_apps_models': True,
    'show_menu_related_apps_models_actions': True,
    'show_menu_related_apps_models_actions_icons': True,
    'show_menu_related_apps_models_actions_tooltips': True,
    'show_menu_related_apps_models_actions_shortcuts': True,
    'show_menu_related_apps_models_actions_shortcuts_icons': True,
    'show_menu_related_apps_models_actions_shortcuts_tooltips': True,
}

# JET UI Theme Settings
JET_UI_THEME = {
    'primary_color': '#008374',
    'secondary_color': '#00796b',
    'accent_color': '#f85a40',
    'font_family': 'Poppins, sans-serif',
    'font_size': '14px',
    'font_weight': '400',
    'line_height': '1.5',
    'border_radius': '8px',
    'box_shadow': '0 2px 4px rgba(0,0,0,0.1)',
    'transition': 'all 0.3s ease',
}

# JET UI Layout Settings
JET_UI_LAYOUT = {
    'sidebar_width': '250px',
    'sidebar_collapsed_width': '60px',
    'content_padding': '20px',
    'content_max_width': '1200px',
    'content_min_width': '800px',
    'content_margin': '0 auto',
    'content_background': '#ffffff',
    'content_border_radius': '8px',
    'content_box_shadow': '0 2px 4px rgba(0,0,0,0.1)',
}

# JET UI Component Settings
JET_UI_COMPONENTS = {
    'button': {
        'border_radius': '8px',
        'padding': '8px 16px',
        'font_weight': '500',
        'transition': 'all 0.3s ease',
    },
    'card': {
        'border_radius': '8px',
        'box_shadow': '0 2px 4px rgba(0,0,0,0.1)',
        'padding': '20px',
        'margin': '10px 0',
    },
    'table': {
        'border_radius': '8px',
        'box_shadow': '0 2px 4px rgba(0,0,0,0.1)',
        'padding': '20px',
        'margin': '10px 0',
    },
    'form': {
        'border_radius': '8px',
        'box_shadow': '0 2px 4px rgba(0,0,0,0.1)',
        'padding': '20px',
        'margin': '10px 0',
    },
}

# Cache configuration
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# Channel Layer Configuration
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}